// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package dev.buzenets.walletserver.grpc;

public interface BalanceSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wallet.BalanceSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;string, string&gt; amount = 1;</code>
   */
  int getAmountCount();
  /**
   * <code>map&lt;string, string&gt; amount = 1;</code>
   */
  boolean containsAmount(
      java.lang.String key);
  /**
   * Use {@link #getAmountMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAmount();
  /**
   * <code>map&lt;string, string&gt; amount = 1;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAmountMap();
  /**
   * <code>map&lt;string, string&gt; amount = 1;</code>
   */

  java.lang.String getAmountOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; amount = 1;</code>
   */

  java.lang.String getAmountOrThrow(
      java.lang.String key);
}
