// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package dev.buzenets.walletserver.grpc;

/**
 * Protobuf type {@code wallet.BalanceSummary}
 */
public  final class BalanceSummary extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wallet.BalanceSummary)
    BalanceSummaryOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BalanceSummary.newBuilder() to construct.
  private BalanceSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BalanceSummary() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BalanceSummary(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              amount_ = com.google.protobuf.MapField.newMapField(
                  AmountDefaultEntryHolder.defaultEntry);
              mutable_bitField0_ |= 0x00000001;
            }
            com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
            amount__ = input.readMessage(
                AmountDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
            amount_.getMutableMap().put(
                amount__.getKey(), amount__.getValue());
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.buzenets.walletserver.grpc.WalletProto.internal_static_wallet_BalanceSummary_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapField internalGetMapField(
      int number) {
    switch (number) {
      case 1:
        return internalGetAmount();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.buzenets.walletserver.grpc.WalletProto.internal_static_wallet_BalanceSummary_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.buzenets.walletserver.grpc.BalanceSummary.class, dev.buzenets.walletserver.grpc.BalanceSummary.Builder.class);
  }

  public static final int AMOUNT_FIELD_NUMBER = 1;
  private static final class AmountDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                dev.buzenets.walletserver.grpc.WalletProto.internal_static_wallet_BalanceSummary_AmountEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> amount_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetAmount() {
    if (amount_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          AmountDefaultEntryHolder.defaultEntry);
    }
    return amount_;
  }

  public int getAmountCount() {
    return internalGetAmount().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; amount = 1;</code>
   */

  public boolean containsAmount(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    return internalGetAmount().getMap().containsKey(key);
  }
  /**
   * Use {@link #getAmountMap()} instead.
   */
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getAmount() {
    return getAmountMap();
  }
  /**
   * <code>map&lt;string, string&gt; amount = 1;</code>
   */

  public java.util.Map<java.lang.String, java.lang.String> getAmountMap() {
    return internalGetAmount().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; amount = 1;</code>
   */

  public java.lang.String getAmountOrDefault(
      java.lang.String key,
      java.lang.String defaultValue) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAmount().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; amount = 1;</code>
   */

  public java.lang.String getAmountOrThrow(
      java.lang.String key) {
    if (key == null) { throw new java.lang.NullPointerException(); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetAmount().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetAmount(),
        AmountDefaultEntryHolder.defaultEntry,
        1);
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetAmount().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      amount__ = AmountDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, amount__);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.buzenets.walletserver.grpc.BalanceSummary)) {
      return super.equals(obj);
    }
    dev.buzenets.walletserver.grpc.BalanceSummary other = (dev.buzenets.walletserver.grpc.BalanceSummary) obj;

    if (!internalGetAmount().equals(
        other.internalGetAmount())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetAmount().getMap().isEmpty()) {
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + internalGetAmount().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.buzenets.walletserver.grpc.BalanceSummary parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.buzenets.walletserver.grpc.BalanceSummary parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.buzenets.walletserver.grpc.BalanceSummary parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.buzenets.walletserver.grpc.BalanceSummary parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.buzenets.walletserver.grpc.BalanceSummary parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.buzenets.walletserver.grpc.BalanceSummary parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.buzenets.walletserver.grpc.BalanceSummary parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.buzenets.walletserver.grpc.BalanceSummary parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.buzenets.walletserver.grpc.BalanceSummary parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static dev.buzenets.walletserver.grpc.BalanceSummary parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.buzenets.walletserver.grpc.BalanceSummary parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static dev.buzenets.walletserver.grpc.BalanceSummary parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.buzenets.walletserver.grpc.BalanceSummary prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wallet.BalanceSummary}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wallet.BalanceSummary)
      dev.buzenets.walletserver.grpc.BalanceSummaryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.buzenets.walletserver.grpc.WalletProto.internal_static_wallet_BalanceSummary_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetAmount();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMutableMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableAmount();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.buzenets.walletserver.grpc.WalletProto.internal_static_wallet_BalanceSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.buzenets.walletserver.grpc.BalanceSummary.class, dev.buzenets.walletserver.grpc.BalanceSummary.Builder.class);
    }

    // Construct using dev.buzenets.walletserver.grpc.BalanceSummary.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      internalGetMutableAmount().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.buzenets.walletserver.grpc.WalletProto.internal_static_wallet_BalanceSummary_descriptor;
    }

    @java.lang.Override
    public dev.buzenets.walletserver.grpc.BalanceSummary getDefaultInstanceForType() {
      return dev.buzenets.walletserver.grpc.BalanceSummary.getDefaultInstance();
    }

    @java.lang.Override
    public dev.buzenets.walletserver.grpc.BalanceSummary build() {
      dev.buzenets.walletserver.grpc.BalanceSummary result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.buzenets.walletserver.grpc.BalanceSummary buildPartial() {
      dev.buzenets.walletserver.grpc.BalanceSummary result = new dev.buzenets.walletserver.grpc.BalanceSummary(this);
      int from_bitField0_ = bitField0_;
      result.amount_ = internalGetAmount();
      result.amount_.makeImmutable();
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.buzenets.walletserver.grpc.BalanceSummary) {
        return mergeFrom((dev.buzenets.walletserver.grpc.BalanceSummary)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.buzenets.walletserver.grpc.BalanceSummary other) {
      if (other == dev.buzenets.walletserver.grpc.BalanceSummary.getDefaultInstance()) return this;
      internalGetMutableAmount().mergeFrom(
          other.internalGetAmount());
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      dev.buzenets.walletserver.grpc.BalanceSummary parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (dev.buzenets.walletserver.grpc.BalanceSummary) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> amount_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAmount() {
      if (amount_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AmountDefaultEntryHolder.defaultEntry);
      }
      return amount_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMutableAmount() {
      onChanged();;
      if (amount_ == null) {
        amount_ = com.google.protobuf.MapField.newMapField(
            AmountDefaultEntryHolder.defaultEntry);
      }
      if (!amount_.isMutable()) {
        amount_ = amount_.copy();
      }
      return amount_;
    }

    public int getAmountCount() {
      return internalGetAmount().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; amount = 1;</code>
     */

    public boolean containsAmount(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetAmount().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAmountMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAmount() {
      return getAmountMap();
    }
    /**
     * <code>map&lt;string, string&gt; amount = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAmountMap() {
      return internalGetAmount().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; amount = 1;</code>
     */

    public java.lang.String getAmountOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAmount().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; amount = 1;</code>
     */

    public java.lang.String getAmountOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAmount().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public Builder clearAmount() {
      internalGetMutableAmount().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; amount = 1;</code>
     */

    public Builder removeAmount(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAmount().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
    getMutableAmount() {
      return internalGetMutableAmount().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; amount = 1;</code>
     */
    public Builder putAmount(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      if (value == null) { throw new java.lang.NullPointerException(); }
      internalGetMutableAmount().getMutableMap()
          .put(key, value);
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; amount = 1;</code>
     */

    public Builder putAllAmount(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableAmount().getMutableMap()
          .putAll(values);
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wallet.BalanceSummary)
  }

  // @@protoc_insertion_point(class_scope:wallet.BalanceSummary)
  private static final dev.buzenets.walletserver.grpc.BalanceSummary DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.buzenets.walletserver.grpc.BalanceSummary();
  }

  public static dev.buzenets.walletserver.grpc.BalanceSummary getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BalanceSummary>
      PARSER = new com.google.protobuf.AbstractParser<BalanceSummary>() {
    @java.lang.Override
    public BalanceSummary parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BalanceSummary(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BalanceSummary> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BalanceSummary> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.buzenets.walletserver.grpc.BalanceSummary getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

